name: habit_tracker
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_svg: ^2.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.1
  equatable: ^2.0.5
  page_flip_builder: ^0.1.3
  sliding_up_panel: ^2.0.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
